# Generated by Django 4.1 on 2022-08-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Man',
        ),
    ]
