# Generated by Django 4.1 on 2022-08-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('woman_wear', 'woman_wear'), ('man_wear', 'man_wear'), ('kid_wear', 'kid_wear')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_prise', models.PositiveIntegerField()),
                ('product_discount', models.PositiveIntegerField()),
                ('product_size', models.CharField(max_length=100)),
                ('product_color', models.CharField(max_length=100)),
                ('product_disc', models.TextField()),
                ('product_image', models.ImageField(upload_to='media/product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
