# Generated by Django 4.1 on 2022-08-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_clothes',
            name='product_cprise',
            field=models.PositiveIntegerField(default=234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_clothes',
            name='product_image',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
